profile/urls.py
from django.conf.urls.defaults import *
from views import *

"""
  A url beginning with /home/ will be redirected to this profile app url list.
"""

urlpatterns = patterns('',
    # View the user's homepage.
    (r'^$', 'profile.views.index'),
    # Search for a course in the database.
    (r'^/course_search/$', 'profile.views.course_search'),
    # Register a student for a course.
    (r'^/add_course/$', 'profile.views.add_course'),
    # View a course group.
    (r'^/course_group/$', 'profile.views.course_group'),
    # View and change your profile and privacy settings.
    (r'^/settings/$', 'profile.views.settings'),
    # Save changes to a Student profile.
    (r'^/settings/edit_personal_info/', 'profile.views.edit_personal_info'),
    # Save changes to privacy settings.
    (r'^/settings/edit_privacy_settings/', 'profile.views.edit_privacy_settings'),
    # View a user's public profile.
    (r'^/profile/(?P<student_id>\d+)/', 'profile.views.profile_page'),
    # View past ratings for a course.
    (r'^/ratings/(?P<course_id>\d+)/', 'profile.views.ratings'),
    # Save a new rating record for a course.
    (r'^/edit_ratings/', 'profile.views.edit_ratings'),
    # View past reccomendations for a course.
    (r'^/recommendations/(?P<course_id>\d+)/', 'profile.views.recommendations'),
    # Save a new reccomendation record for a course.
    (r'^/edit_recommendations/', 'profile.views.edit_recommendations'),
    # View your private messages.
    (r'^/message/(?P<student_id>\d+)/(?P<previous_message_id>\d+)/', 'profile.views.message'),
    # Send a private message.
    (r'^/send_message/', 'profile.views.send_message'),
    # View a specific private message.
    (r'^/view_message/(?P<message_id>\d+)/', 'profile.views.view_message'),
    # Create a new study group.
    (r'^/create_study_group/', 'profile.views.create_study_group'),
    # View a study group's details and members.
    (r'^/view_study_group/(?P<study_group>\w+)/', 'profile.views.view_study_group'),
    # Make a reccomendation for a course.
    (r'^/course_recommendation/(?P<student_id>\d+)/', 'profile.views.course_recommendation'),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.contrib.auth.views import  logout
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

'''
    This file defines a tuple that Django uses to direct HTTP Requests to the proper view.
    Note that 'profile.urls' is included for the '^home' regex.
    This means that any urls of the form "http://www.StudentCityURL.com/home/..." are redirected to the profile module.
'''

urlpatterns = patterns('',
    # The main login/register page
    url(r'^$', 'authentication.views.index'),
    # The view that handles the registration of a new user
    url(r'^register/', 'authentication.views.register'),

    # The view that will one day handle user login
    url(r'^login', 'authentication.views.login'),
    # The view that handles user logout
    url(r'^logout', logout),

    # The profile views, imported from profile/urls.py
    url(r'^home', include('profile.urls')),
    
    # The admin site
    url(r'^admin/', include(admin.site.urls)),
    # The admin docs
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Serving static files
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    
    # File Upload
    (r'^fileupload/', 'fileupload.views.upload_file'),
)

Profile/models.py
from django.db import models

class Course(models.Model):
    course_department = models.CharField(max_length=16)
    course_number = models.IntegerField()
    course_name = models.CharField(max_length=256)
    course_description = models.TextField()
    
    def course_code(self):
        return course_department + " " + str(course_number)


class Student(models.Model):
    rcs_id = models.CharField(max_length=128)
    first_name = models.CharField(max_length=256)
    middle_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256)
    class_year = models.CharField(max_length=4)
    rin = models.CharField(max_length=9)
    profile_picture_url = models.CharField(max_length=512)
    classes_current = models.ManyToManyField(Course)
    classes_taken = models.ManyToManyField(CourseDetail)
    
    def name(self):
        return self.first_name + self.middle_name + self.last_name


class CourseDetail(models.Model):
    SEMESTER_CHOICES = (
        ('F', 'Fall'),
        ('S', 'Spring'),
    )
    course = models.ForeignKey(Course)
    year = models.CharField(max_length=4)
    semester = models.CharField(max_length=1, choices=SEMESTER_CHOICES)
    section = models.IntegerField()

class Teacher(models.Model):
    rcs_id = models.CharField(max_length=128)
    first_name = models.CharField(max_length=256)
    middle_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256)
    courses_taught = models.ManyToManyField(CourseDetail)
    def name(self):
        return self.first_name + self.middle_name + self.last_name

profile/models.py
# -*- coding: utf-8 -*-
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.forms import ModelForm


"""
    This file contains all of the Models used for the user profile, the course group,
    the messaging system, and essentially everything else other than the authentication system and the file upload.
"""



SEMESTER_CHOICES = (
    ('F', 'Fall'),
    ('S', 'Spring'),
    ('B', 'Summer')
)

RECOMMEND_COURSE_CHOICES = (
    ('Y', 'Yes'),
    ('N', 'No'),
)

RATINGS_CHOICES = (
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
)


class Course(models.Model):
    """Store data regarding a course offered by the university."""
    course_department = models.CharField(max_length=16)
    course_number = models.IntegerField()
    course_name = models.CharField(max_length=256)
    course_description = models.TextField()
    
    def course_code(self):
        return self.course_department + " " + str(self.course_number)

    def get_num_students(self, past_or_present):
	"""Return the number of students who are currently taking or have taken the course, pased on the past_or_present var."""
	date_time = datetime.now()
        if date_time.month in (1, 2, 3, 4, 5, 6):
            sem = 'S'
        else:
            sem = 'F'
        yr = date_time.year
        count = 0
        if (past_or_present == 'present'):
            course_detail = self.coursedetail_set.filter(year__exact=yr, semester__exact=sem)
            for cd in course_detail:
                count += cd.current.count()
        elif (past_or_present == 'past'):
            course_detail = self.coursedetail_set.exclude(year__exact=yr, semester__exact=sem)
            for cd in course_detail:
                count += cd.taken.count()
        return count

    def __unicode__(self):
        return self.course_name


class CourseDetail(models.Model):
    """Store data regarding a specific section of a course within a specific semester of a specific year."""
    course = models.ForeignKey(Course)
    year = models.CharField(max_length=4)
    semester = models.CharField(max_length=1, choices=SEMESTER_CHOICES)
    section = models.IntegerField()
    professor = models.ManyToManyField('Teacher')
    crn = models.PositiveIntegerField(unique=True)

    def __unicode__(self):
        return self.course.course_name + " " + self.semester + " " + self.year + " " + str(self.section)
    
    def get_num_current_students(self):
        num = self.course.get_num_students(past_or_present='present')
        return num

    def get_num_past_students(self):
        num = self.course.get_num_students(past_or_present='past')
        return num

class Student(models.Model):
    """Store data regarding a student attending the university."""
    user = models.ForeignKey(User, unique=True)
    rcs_id = models.CharField(max_length=128)
    rin = models.CharField(max_length=9)


    first_name = models.CharField(max_length=256, blank=True)
    middle_name = models.CharField(max_length=256, blank=True)
    last_name = models.CharField(max_length=256, blank=True)
    class_year = models.CharField(max_length=4, blank=True)
    interests = models.TextField(max_length=1280, blank=True)
    clubs = models.TextField(max_length=1280, blank=True)
    profile_picture_url = models.URLField(blank=True, default='http://localhost:8000/static/images/default_profile_picture.png')
    classes_current = models.ManyToManyField(CourseDetail, related_name='current')
    classes_taken = models.ManyToManyField(CourseDetail, related_name='taken')

    def add_course(self, dept, num, section, semester, year, present_or_past):
        course = Course.objects.get(course_number=num, course_department=dept)
        course_detail = CourseDetail.objects.get(course=course, semester=semester, year=year, section=section)
        if (present_or_past == 'present'):
            self.classes_current.add(course_detail)
        else:
            self.classes_taken.add(course_detail)

    def name(self):
        return self.first_name + " " + self.middle_name + " " + self.last_name

    def __unicode__(self):
        return self.rcs_id

class Teacher(models.Model):
    """Store data regarding a teacher employed by the university."""
    rcs_id = models.CharField(max_length=128)
    first_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256)
    courses_taught = models.ManyToManyField(CourseDetail)
    def name(self):
        return self.first_name + self.last_name
    def __unicode__(self):
        return self.rcs_id

class PrivacySettings(models.Model):
    """Store data regarding a student's privacy settings."""
    student = models.ForeignKey(Student, unique=True)
    allow_others_to_view_profile_picture = models.BooleanField()
    allow_others_to_view_interests = models.BooleanField()
    allow_others_to_view_clubs = models.BooleanField()
    allow_others_to_send_me_messages = models.BooleanField()
    allow_others_to_send_me_email = models.BooleanField()
    allow_others_to_view_classes = models.BooleanField()

    
class PrivateMessage(models.Model):
    """Store data regarding the contents of a private, user-to-user message."""
    author = models.ForeignKey(Student, related_name='PM_author')
    recipients = models.ManyToManyField(Student, related_name='PM_recipients')
    subject = models.CharField(max_length=256)
    contents = models.TextField()
    read = models.BooleanField()
    previous_message = models.PositiveIntegerField(blank=True)
    timestamp = models.DateTimeField()
    
class GroupPost(models.Model):
    """Store data regarding the contents of a post on a group's message board."""
    author = models.ForeignKey(User)
    group = models.ForeignKey(Course)
    contents = models.TextField()
    timestamp = models.TimeField()

class Ratings(models.Model):
    """Store data regarding the ratings a student gives a class."""
    course = models.ForeignKey(CourseDetail)
    rater = models.ForeignKey(Student)
    easiness = models.IntegerField(choices=RATINGS_CHOICES)
    course_material = models.IntegerField(choices=RATINGS_CHOICES)
    course_subject_interest = models.IntegerField(choices=RATINGS_CHOICES)
    timestamp = models.DateTimeField(default=datetime.now)

class Recommendations(models.Model):
    """Store data regarding the contents of a private, user-to-user message."""
    course = models.ForeignKey(CourseDetail)
    recommender = models.ForeignKey(Student)
    would_recommend_course = models.CharField(max_length=1, choices=RECOMMEND_COURSE_CHOICES)
    comments = models.TextField(max_length=256, blank=True)
    timestamp = models.DateTimeField(default=datetime.now)

class StudyGroup(models.Model):
    """Store data regarding information about and the members of a study group."""
    course = models.ForeignKey(Course)
    members = models.ManyToManyField(Student, related_name='study_groups')
    name = models.CharField(max_length=256)
    max_capacity = models.IntegerField()

profile/forms.py
from django import forms
from datetime import datetime
from django.forms import Form, ModelForm
from profile.models import *

"""
    These are the custom forms we developed to go along with our models.
"""

class StudentForm(ModelForm):
    """Generate a form used for saving personal data into the Student model."""
    class Meta:
        model = Student
        fields = ("rcs_id", "first_name", "middle_name", "last_name", "class_year", "profile_picture_url", "interests", "clubs")


class PrivacySettingsForm(ModelForm):
    """Generate a form used for saving student privacy settings into the PrivacySettings object."""
    class Meta:
        model = PrivacySettings
        exclude = ('student')


class CourseSearchForm(Form):
    """Generate a form used for searching the CourseDetail and Course model tables in the SQL database."""
    course_department = forms.CharField(max_length=16)
    course_number = forms.IntegerField(required=False)
    # TODO: Implement course_name search with substring comparison, etc.
    #course_name = forms.CharField()
    year = forms.CharField(max_length=4)
    semester = forms.ChoiceField(choices=SEMESTER_CHOICES)

    section = forms.IntegerField()

class RatingsForm(ModelForm):
    """Generate a form used for saving ratings data into the Ratings model."""
    course = forms.ModelChoiceField(queryset=CourseDetail.objects.all(),widget=forms.HiddenInput())
    rater = forms.ModelChoiceField(queryset=Student.objects.all(),widget=forms.HiddenInput())

    class Meta:
        model = Ratings
        exclude = ("timestamp")

class RecommendationsForm(ModelForm):
    """Generate a form used for saving recommendations data into the Recommendations model."""
    course = forms.ModelChoiceField(queryset=CourseDetail.objects.all(),widget=forms.HiddenInput())
    recommender = forms.ModelChoiceField(queryset=Student.objects.all(),widget=forms.HiddenInput())

    class Meta:
        model = Recommendations
        exclude = ("timestamp")

class MessageForm(ModelForm):
    """Generate a form used for sending a message and saving it in the Message model."""
    author = forms.ModelChoiceField(queryset=Student.objects.all(), widget=forms.HiddenInput())
    previous_message = forms.IntegerField(widget=forms.HiddenInput())
    recipients = forms.ModelMultipleChoiceField(queryset=Student.objects.filter(privacysettings__allow_others_to_send_me_messages__exact=True))

    class Meta:
        model = PrivateMessage
        exclude = ("timestamp", "read")

templates/profile/add_course.html
<!--This template uses the base_with_classes.html file and extends the main content.  The main content is populated with a form to search for courses
and then populate the search results.  The search results are links to add a course to a student when clicked on.-->

{% extends "profile/base_with_classes.html" %}

{% load custom_filters %}
{% block style %}
    td.spacer
    {
        width:      30px;
    }
{% endblock style %}
    

{% block main_content %}
<div id="course_selection_content" style="width:100%; min-height:600px;">
    <h2>Course Search</h2>
    <div id="search">
        <form action="/home/course_search/" method="post">
        {% csrf_token %}
            <table>
                <tr><th>Department:</th><td class="spacer"></td><td>{{ course_search_form.course_department }}</td></tr>
                <tr><th>Course Number:</th><td class="spacer"></td><td>{{ course_search_form.course_number }}</td></tr>
                <tr><th>Year:</th><td class="spacer"></td><td>{{ course_search_form.year }}</td></tr>
                <tr><th>Semester:</th><td class="spacer"></td><td>{{ course_search_form.semester }}</td></tr>
                <tr><th>Section:</th><td class="spacer"></td><td>{{ course_search_form.section }}</td></tr>
                <input class="float_right button_input" type="submit" value="Search" />
            </table>
        </form>
    </div>
    <div id="results">
        <table id="results_table">
        {% if search_results|length > 0 %}
        <tr><td><h2>Search Results:</h2></td></tr>
        <tr>
            <td>Course Name:</td><td class="spacer"></td><td>Course Code:</td><td class="spacer"></td><td>Year:</td><td class="spacer"></td><td>Semester:</td><td class="spacer"></td><td>Section:</td>
        </tr>
        {% for course_detail in search_results %}
        <tr>
            <td>
		<form name="add_{{ course_detail.course.course_code|strip_spaces }}_{{ course_detail.section }}" method="POST" action="/home/add_course/">
		{% csrf_token %}
		<input type="hidden" name="dept" value="{{ course_detail.course.course_department }}" />
		<input type="hidden" name="num" value="{{ course_detail.course.course_number }}" />
		<input type="hidden" name="yr" value="{{ course_detail.year }}" />
		<input type="hidden" name="sem" value="{{ course_detail.semester }}" />
		<input type="hidden" name="sec" value="{{ course_detail.section }}" />
		<a href="javascript:document.add_{{ course_detail.course.course_code|strip_spaces }}_{{ course_detail.section }}.submit()">{{ course_detail.course.course_name }}</a>
		</form>
	    </td>
	    <td class="spacer"></td><td><a href="/home/add_course?dept={{ course_detail.course.course_department }}&num={{ course_detail.course.course_number }}">{{ course_detail.course.course_code }}</a></td><td class="spacer"></td><td>{{ course_detail.year }}</td><td class="spacer"></td><td>{{ course_detail.semester }}</td><td class="spacer"></td><td>{{ course_detail.section }}</td>
        </tr>
        {% endfor %}
        {% endif %}
        </table>
    </div>
</div>
{% endblock main_content %}

templates/profile/course_group.html
<h2>{{ course.name }}</h2>

templates/profile/course_group_main.html
{% extends "profile/base_with_classes.html" %}

{% block script %}
{{ block.super }}
    $(document).ready(function(){
        $(".course_tile").click(function(){
            $.ajax({
                type: 'POST',
                url: '/home/course_group',
                data: {
                    'course_code' :   $(this).attr("id")
                },
                success: loadPage,
                dataType: 'html'
            });
        });
    
    $("#{{  }}").click()
    
    });
    function loadPage(data){
        // build htmlString here with provided json
        $("#course_group_div").html(data)
    }
{% endblock script %}

{% block main_content %}
<div id="course_group_div">
    
</div>
{% endblock main_content %}

templates/profile/course_search.html
{% extends "profile/base.html" %}

{% block left_side %}
    <h3>Classes:</h3>
    {% for course_detail in courses %}
        <div class="course_tile" id="{{ course_detail.course.course_code }}">
            <div class="text">
                <h2>{{ course_detail.course.course_name }}</h2>
                <h6>Currents: {{ course_detail.get_num_current_students }}. | Veterans: {{ course_detail.get_num_past_students }}. </h6>
                </div>
                </div>
            </div>
        </div>

	<div class="search">
	    <form id="search" method="post" action="/course_search">
                {% csrf_token %}
                <table class="float_right">
                    <tr><th><label for="department">Course Department:</label></th><td>{{  course_search.department }}</td></tr>
                    <tr><th><label for="number">Course Number:</label></th><td>{{  course_search.number }}</td></tr>
                    <tr><th><label for="name">Course Name:</label></th><td>{{  course_search.name }}</td></tr>
                    <tr><th><label for="description">Course Description:</label></th><td>{{  course_search.description }}</td></tr>
                </table>
                <input class="float_right button_input" type="submit" value="Search" style="clear:both;" />
            </form>
	</div>
    {% endfor %}
{% endblock left_side %}

templates/profile/ratings.html
{% extends "profile/base_with_classes.html" %}

{% block main_content %}
<div id="ratings_div">
     <h2 class="main_heading">Course Rating</h2>
     <br />
     <form id="ratings_form_id" method="POST" action="/home/edit_ratings/">
           {% csrf_token %}
           <table>{{ ratings_form.as_table }}</table>

           <input class="float_right button_input" type="submit" value="Save" />
     </form>
     <br />
     <h6>Easiness - 1 would mean that the class is extremely hard whereas 5 would mean that the class was extremely easy.</h6>
     <h6>Course Material - 1 would mean that the course material (exams, assignments, readings, etc.) were not effective in aiding in learning whereas a 5 would mean that the course material was effective in aiding in learning.</h6>
     <h6>Course Subject Interest - 1 would mean that the course subject was boring wheras 5 would mean that the course subject was engaging.</h6>
</div>
{% endblock main_content %}

templates/profile/ratings_class.html
<div class="ratings_class">
    <h1 style="font-weight: bold; font-size: 24px;">{{ course_detail.course.course_name }}</h1>
    <br />
    <h1 style="font-weight: bold; font-size: 18px;">Ratings</h1>
    <br />
    <table>
	<tr>
	<th>User</th>
	<th>Easiness</th>
	<th>Course Material</th>
	<th>Course Subject Interest</th>
	<th>Year Taken</th>
	<th>Semeseter Taken</th>
	</tr>
	{% for course in course_detail.course.coursedetail_set.all %}
	{% for rate in course.ratings_set.all %}
	<tr>
	    <td>{{ rate.rater.rcs_id }}</td>
	    <td>{{ rate.easiness }}</td>
	    <td>{{ rate.course_material }}</td>
	    <td>{{ rate.course_subject_interest }}</td>
	    <td>{{ rate.course.year }}</td>
	    <td>{{ rate.course.semester }}</td>
	</tr>
	{% endfor %}
	{% endfor %}
    </table>
    <br/>
    <a href="/home/ratings/{{ course_detail.id }}" style="background-color: #B9E0F7; color: black; padding: 2px; border: 2px solid #0067B1">Rate this Course</a>
</div>

templates/profile/recommendations_class.html
<div class="recommendations_class">
    <h1 style="font-weight: bold; font-size: 24px;">{{ course_detail.course.course_name }}</h1>
    <br />
    <h1 style="font-weight: bold; font-size: 18px;">Recommendations</h1>
    <br />
    <table>
	<tr>
	    <th>User</th>
	    <th>Recommend</th>
	    <th>Comments</th>
	    <th>Year Taken</th>
	    <th>Semeseter Taken</th>
	</tr>
	{% for course in course_detail.course.coursedetail_set.all %}
	{% for recommendation in course.recommendations_set.all %}
	<tr>
	    <td>{{ recommendation.recommender.rcs_id }}</td>
	    <td>{{ recommendation.would_recommend_course }}</td>
	    <td>{{ recommendation.comments }}</td>
	    <td>{{ recommendation.course.year }}</td>
	    <td>{{ recommendation.course.semester }}</td>
	</tr>
	{% endfor %}
	{% endfor %}
    </table>
    <br />
    <a href="/home/recommendations/{{ course_detail.id }}" style="background-color: #B9E0F7; color: black; padding: 2px; border: 2px solid #0067B1">Recommend this Course</a>
</div>

templates/profile/resources_class.html
<!-- This prints out links to all the uploaded resources and a link to upload new resources  -->
{% load custom_filters %}
<div class="resources_class">
    <h1 style="font-weight: bold; font-size: 24px;">{{ course_detail.course.course_name }}</h1>
    {% for x in course_detail.course.course_name|get_resources %}
    <a href="static/userupload/{{course_detail.course.course_name}}/{{x}}">{{x}}</a>
    <br />
    {% endfor %}
    <br /><br />
    <a href="fileupload/upload.html">Upload New Resources</a>
</div>

templates/profile/settings.html
{% extends "profile/base.html" %}

{% block style %}
    #left_side
    {
        background-color:   #0067B1;
        position:           absolute;
        top:                173px; 
        left:               400px;
        float:              none;
        box-shadow:         0px 0px 0px 0px #0067B1;
    }
    .course_tile
    {
        background-image:   url(/static/images/course_tile.png);
    }
    td.spacer
    {
        width:              30px;
    }
{% endblock style %}
    

{% block script %}
    $(document).ready(function(){
        $('#personal').hide();
        $('#privacy').hide();
        $('#personal_info').click(function(){
            $('#personal').show();
            $('#privacy').hide();
            $( ".course_tile" ).css( "background-image", "url(/static/images/course_tile.png)" );
            $(this).css( "background-image", "url(/static/images/course_tile_long.png)" );
        });
        $('#privacy_set').click(function(){
            $('#personal').hide();
            $('#privacy').show();
            $( ".course_tile" ).css( "background-image", "url(/static/images/course_tile.png)" );
            $(this).css( "background-image", "url(/static/images/course_tile_long.png)" );
        });

        
        // Force a click event on Personal Information:
        $('#personal_info').click();
    });
{% endblock script %}
    
{% block left_side %}
<div id="settings_options">
     <ul>
         <li class="course_tile" id="personal_info">
         <div class="text">
              <h2>Personal Information</h2>
         </div>
         </li>
         <li class="course_tile" id="privacy_set">
         <div class="text">
              <h2>Privacy Settings</h2>
         </div>
         </li>
     </ul>
</div>
{% endblock left_side %}

{% block main_content %}
<div id="settings_content" style="width:100%; min-height:600px;">
     <div id="personal">
          <h2 class="main_heading">Personal Information</h2><br />
          <form id="personal_info" method="POST" action="/home/settings/edit_personal_info/">
          {% csrf_token %}
                <table>
                    <tr><th><label for="id_first_name">First Name:</label></th><td class="spacer"></td><td>{{ personal_form.first_name }}</td></tr>
                    <tr><th><label for="id_middle_name">Middle Name:</label></th><td class="spacer"></td><td>{{ personal_form.middle_name }}</td></tr>
                    <tr><th><label for="id_last_name">Last Name:</label></th><td class="spacer"></td><td>{{ personal_form.last_name }}</td></tr>
                    <tr><th><label for="id_rcs_id">RCS ID:*</label></th><td class="spacer"></td><td>{{ personal_form.rcs_id }}</td></tr>
                    <tr><th><label for="id_class_year">Class Year:</label></th><td class="spacer"></td><td>{{ personal_form.class_year }}</td></tr>
                    <tr><th><label for="id_profile_picture_url">Profile Picture:</label></th><td class="spacer"></td><td>{{ personal_form.profile_picture_url }}</td></tr>
                    <tr><th><label for="id_interests">Interests:</label></th><td class="spacer"></td><td>{{ personal_form.interests }}</td></tr>
                    <tr><th><label for="id_clubs">Clubs:</label></th><td class="spacer"></td><td>{{ personal_form.clubs }}</td></tr>
                </table>
                <input class="float_right button_input" type="submit" value="Save" />
          </form>
          <br />
          <p>Separate interests and clubs by a ","</p>
          <p>*RCS_ID is required</p>
     </div>
     <div id="privacy">
          <h2 class="main_heading">Privacy</h2>
          <form id="personal_info" method="POST" action="/home/settings/edit_privacy_settings/">
                {% csrf_token %}
                <table>{{ privacy_form.as_table }}</table>

                <input class="float_right button_input" type="submit" value="Save" />
          </form>
     </div>
</div>
{% endblock main_content %}

templates/profile/study_group_class.html
<div class="study_group_class">
    <h1 style="font-weight: bold; font-size: 24px;">{{ course_detail.course.course_name }}</h1>
    <br />
    <h1 style="font-weight: bold; font-size: 18px;">Study Groups</h1><br /><br />
    
    {% for sg in course_detail.course.studygroup_set.all %}
    <p style="font-size: 14px;">{{ sg.name }}</p>
    {% endfor %}
    <p style="font-weight: bold; font-size: 16px;"> Create a New Study Group:</p>
    

    <form method="POST" action="/home/create_study_group/">
	{% csrf_token %}
	<input type="hidden" name="course_code" value="{{ course_detail.course.course_code }}" />
	<table>
	    <tr><td>
	        <table>
		    <tr>
		        <td><label for="sg_title">Title:</label></td><td><input type="text" name="sg_title" /></td>
		    </tr>
		    <tr>
		        <td><label for="max_capacity">Max Capacity:</label></td><td><input type="text" name="max_capacity" /></td>
		    </tr>
	        </table>
	    </td></tr>
	    <tr><td>
	        <table>
		    <tr>
		        <td>Current Students: (click to add)</td>
		    </tr>
		    <tr>
		        <td>
                            <div id="course_students">
			    {% for course in course_detail.course.coursedetail_set.all %}
			    {% for person in course.current.all %}
			        <div class="person_block flipflop" id="{{ person.id }}">
				    <img class="person_image" src="{{ person.profile_picture_url }}" />
				    <h5 class="person_name">{{ person.first_name }} {{ person.last_name }}</h5><br />
				    <input type="checkbox" class="course_students_checkbox" name="course_students" value="{{ person.id }}" />
			        </div>
			    {% endfor %}
			    {% endfor %}
			    </div>
		        </td>
		    </tr>
		    <tr>
		        <td style="text-align:right;"><input type="submit" id="sg_submit"></td>
	            </tr>
	        </table>
            </td></tr>
        </table>

	<div class="popup_overlay" id="po_hidden" >
	</div>

	</form>

</div>

templates/profile/view_study_group.html
{% extends "profile/base_with_classes.html" %}

{% block main_content %}
<span style="font-weight: bold; font-size: 16px;">Study Group:</span><br /><br />
<h1 style="font-weight: bold; font-size: 24px;">{{ study_group.course_name }}</h1><br /><br />
<p>Course:  {{ study_group.course.course_name }}</p>
<p>Max Capacity:  {{ study_group.max_capacity }}</p>
<p></p>
<span style="font-weight: bold; font-size: 12px;">Members:</span><br /><br />
{% for member in study_group.members.all %}
<p><a href="/home/profile/{{ person.id }}">{{ member.name }}</a><p>
{% endfor %}
{% endblock main_content %}